// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBekNIDKY7d1pzZPUvVxiPAKEl3rMcEpFI',
    appId: '1:902428528936:web:8b41a93a0968f88c5dc01d',
    messagingSenderId: '902428528936',
    projectId: 'farmwasteconnect',
    authDomain: 'farmwasteconnect.firebaseapp.com',
    storageBucket: 'farmwasteconnect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoe7fEhrhUXBQQDi2cCSuTRp2Th9DGmKc',
    appId: '1:902428528936:android:b638891b6abadeb25dc01d',
    messagingSenderId: '902428528936',
    projectId: 'farmwasteconnect',
    storageBucket: 'farmwasteconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeArcUTO36CISKFrg5EKUlKTTrA-DcPpY',
    appId: '1:902428528936:ios:a42a48200e8956635dc01d',
    messagingSenderId: '902428528936',
    projectId: 'farmwasteconnect',
    storageBucket: 'farmwasteconnect.firebasestorage.app',
    iosBundleId: 'com.example.farmWasteConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeArcUTO36CISKFrg5EKUlKTTrA-DcPpY',
    appId: '1:902428528936:ios:a42a48200e8956635dc01d',
    messagingSenderId: '902428528936',
    projectId: 'farmwasteconnect',
    storageBucket: 'farmwasteconnect.firebasestorage.app',
    iosBundleId: 'com.example.farmWasteConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBekNIDKY7d1pzZPUvVxiPAKEl3rMcEpFI',
    appId: '1:902428528936:web:e6c92bc081bc5b0a5dc01d',
    messagingSenderId: '902428528936',
    projectId: 'farmwasteconnect',
    authDomain: 'farmwasteconnect.firebaseapp.com',
    storageBucket: 'farmwasteconnect.firebasestorage.app',
  );
}
